### PR TITLE
add: slider and toast

### PR DESCRIPTION
**Pull request by Shivani-1524**
Added Slider and Toast Components with their respective JS.

### CODE REVIEW

**Comment by swstica** [comment]
Don't think any changes are required, overall the website looks great. 
Good work Shivani:)

**Review by rahulk31 — COMMENTED** [review]
Looks Great to me, Merge ready PR 👍

**Comment by Shivani-1524** [comment]
> Don't think any changes are required, overall the website looks great. Good work Shivani:)

Thank you Swastika! :)

**Comment by Shivani-1524** [comment]
> Looks Great to me, Merge ready PR 👍

okay thanks :)

**Pull request merged**
